version: "3"

services:
  webservice:
    build: "."
    container_name: webservice
    volumes:
      - .:/webservice
      - /webservice/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ".environment/.dev.env"
    restart: always
